### ISSUE TITLE
Unable to create credential with context https://schema.org

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/verifiable-data#109]
When I added the https://schema.org to the credential context. The following error occurred 
  "type": "jsonld.InvalidUrl",
      "details": "Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context."

How to write the documentLoader to support https://schema.org for the following credential
 ```
{
  "credential": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
       "https://schema.org"
    ],
    "type": [
      "VerifiableCredential",
      "CourseCredential"
    ],
    "issuer": {
      "id": "did:key:z6MkndAHigYrXNpape7jgaC7jHiWwxzB3chuKUGXJg2b5RSj",
    },
    "issuanceDate": "2021-07-26T01:05:05.152Z",
    "credentialSubject": {
      "id": "did:key:z6MkfxQU7dy8eKxyHpG267FV23agZQu9zmokd8BprepfHALi",
      "givenName": "Chris",
      "familyName": "Shin",
      "educationalCredentialAwarded": "Certificate Name"
    },
  }
}
```

**Comment by OR13** [comment]
See https://webmasters.stackexchange.com/questions/123409/how-can-http-schema-org-be-used-in-json-lds-context-even-though-its-not-a

and https://schema.org/docs/developers.html


However, you should not be downloading the entire schema.org context via a document loader that makes network requests, and you should not be bundling the entire schema.org vocabulary into you application.
instead, you should define a context that uses schema.org terms that are needed for your credential type... or use `@vocab` to turn off json-ld processing.

Here are some helpful examples:

A term defined by schema.org: https://github.com/w3c-ccg/citizenship-vocab/blob/main/contexts/citizenship-v1.jsonld#L8
A term defined by a custom vocab: https://github.com/w3c-ccg/citizenship-vocab/blob/main/contexts/citizenship-v1.jsonld#L12

An example credential using a custom context: https://w3c-ccg.github.io/citizenship-vocab/#example

**Comment by thomas-tran** [comment]
Thanks
