### ISSUE TITLE
compactProof should NEVER be set to true

### ISSUE THREAD

**Issue by acarnagey** [transmute-industries/verifiable-data#112]
When using the non default options for verifying a mill test report verifiable credential, specifically compactProof, results in a failure to verify.
compactProof: true with expansionMap: undefined or true results in the error `The property "grade" in the input was not defined in the context.`
compactProof: true with expansionMap: false results in an `invalid signature`.  All other expansionMap and compactProof result in successful verification.

**Comment by OR13** [comment]
The issue was caused by setting compactProof to true, it should NEVER be set to true. 

Preprocessing the JSON differently will break the signature, as expected.

TLDR never set compactProof to true.

**Comment by OR13** [comment]
I think we want to basically warn and test this behavior, (compactProof configuration), but not remove it... although I could probably be convinced to remove it...

**Comment by acarnagey** [comment]
I am leaning towards removing the compactProof option entirely.  Since we are using digital bazaar as our source and since they have removed this option entirely, it is not needed.  If we keep this option but do not use it, it can be confusing to a developer as to why this option is there if not used, we should remove unneeded code to make the code easier to understand basically.
