### ISSUE TITLE
Credential issuer must match the verification method controller

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/verifiable-data#114]
Hi @OR13,

I tried to create signing key and passed to sidetree element did method to generate the did e.g.

did:elem:ganache:EiD351yY0XqnbCJN2MaZSQJMgG-bqmgFMDRGKawfu6_mZA

I used the same key to create the credential with the result

```
{
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/jws-2020/v1"
      ],
      "id": "http://example.edu/credentials/3732",
      "type": ["VerifiableCredential"],
      "issuer": {
        "id": "did:elem:ganache:EiD351yY0XqnbCJN2MaZSQJMgG-bqmgFMDRGKawfu6_mZA"
      },
      "issuanceDate": "2010-01-01T19:23:24Z",
      "credentialSubject": { "id": "did:example:ebfeb1f712ebc6f1c276e12ec21" },
      "proof": {
        "type": "JsonWebSignature2020",
        "created": "2010-01-01T19:23:24Z",
        "verificationMethod": "did:key:z6MkokrsVo8DbGDsnMAjnoHhJotMbDZiHfvxM4j65d8prXUr#z6MkokrsVo8DbGDsnMAjnoHhJotMbDZiHfvxM4j65d8prXUr",
        "proofPurpose": "assertionMethod",
        "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..k_7t6h5IGSWFAqIlqru3zyZ0FDPQGo88p9jDeKC1yw8oxd7xj6B70tZNSaspWkMyWbXFmZ5yCO8dlZZ9_kKbAQ"
      }
    },
```
However, during the verification, there was an error: Credential issuer must match the verification method controller.

The documentLoader can resolve the did:elem:ganache:EiD351yY0XqnbCJN2MaZSQJMgG-bqmgFMDRGKawfu6_mZA and return the diddocument from the sidetree and it also can resolve the verificationMethod in the proof did:key:z6MkokrsVo8DbGDsnMAjnoHhJotMbDZiHfvxM4j65d8prXUr#z6MkokrsVo8DbGDsnMAjnoHhJotMbDZiHfvxM4j65d8prXUr.

**Comment by OR13** [comment]
`did:elem:ganache:EiD351yY0XqnbCJN2MaZSQJMgG-bqmgFMDRGKawfu6_mZA` != `did:key:z6MkokrsVo8DbGDsnMAjnoHhJotMbDZiHfvxM4j65d8prXUr`
