### ISSUE TITLE
@transmute/ed25519-signature-2018 complains on wrong date when using toISOString

### ISSUE THREAD

**Issue by vongohren** [transmute-industries/verifiable-data#125]
The lib says that toISOString of new Date is wrong format, and It is because of the . fractions on the seconds that toISOString produces.

But according to the spec: https://www.w3.org/TR/xmlschema11-2/#nt-seFrag, that is a valid format?

And is not this the time format the verifiable credentials following?

It only seems to accepts this format "YYYY-MM-DDTHH:mm:ss[Z]"

Where the [Z] is just a string. This test running does not accepte offsetData such as +0100 which is pretty critical

**Comment by vongohren** [comment]
Okok, so the warnings are nessecarily not right anymore? As this should allow timezone and fractions? Based on the dateTime? I might be able to do a PR but just need to confirm with you that it is allowed now

**Comment by OR13** [comment]
I think the warning are not needed any more, the spec now says "XML Date Time" which is a subset of ISO 8601... IMO, there should be no warnings when using strings that are valid XML Date Time s.

**Comment by BenjaminMoe** [comment]
I think technically the standard allows for ISO strings. The main reason we're using XML date strings with no milliseconds is to maintain compatibility with Digital Bazaar, to produce the same exact output for a given input.

The test vectors are generated here: https://github.com/transmute-industries/verifiable-data/blob/main/packages/ed25519-signature-2018/scripts/digital-bazaar.date-fixture.js
And the test is here: https://github.com/transmute-industries/verifiable-data/blob/main/packages/ed25519-signature-2018/src/__tests__/date.test.ts

In principal ISO 8601 makes a lot more sense. Multiple credentials can be signed per second, so having milliseconds would generate a unique timestamp. Having the timezone offset would provide more context of where the proof was created, further increasing the chances of the timestamp being unique. 

We wanted to do the same thing for consistency, and then explain the reason why we don't agree with it. In this case, we'd prefer to use ISO 8601, and be able to call `date.toISOString()` for a valid date.

**Comment by vongohren** [comment]
@BenjaminMoe okok, but the XML standard: https://www.w3.org/TR/xmlschema-2/#dateTime allows for fractions, or miliseconds which you call them?

But DigitalBazar dont allow for that and why this warning was there intially?

So be xml dateTime compliant without fractions?

But digital bazar has fractions/milliseconds? https://github.com/transmute-industries/verifiable-data/blob/main/packages/ed25519-signature-2018/scripts/digital-bazaar.date-fixture.js#L98

Or what am I not seeing here :P

**Comment by OR13** [comment]
@vongohren the warning is there because the spec did not specify XML Date time originally.

The warning should be removed for any string fields that are valid XML Date Times... all XML Date Time are valid ISO8601 strings.

@BenjaminMoe is referring to the behavior... https://github.com/digitalbazaar/jsonld-signatures/blob/fe51dcfcd4567b364a99626cdbe2aa136aae0ab7/lib/util.js#L23

Which is questionable, but AFAIK it should not result in a warning.

**Comment by vongohren** [comment]
@OR13 ah okok! So that line does look questionable and not updated with new spec no.

But I will see if I can get to this soon

**Comment by OR13** [comment]
We basically don't support this suite anymore
