### ISSUE TITLE
Is this suppose to fail?

### ISSUE THREAD

**Issue by vongohren** [transmute-industries/verifiable-data#129]
I have a VC that is trying to stick to JSON LD structure, and should really fail accroding to: https://github.com/transmute-industries/verifiable-data/blob/main/packages/jsonld-schema/src/check/check.ts#L68

But this is not failing with the current library any idea why?
Im trying to understand how the context and the type stick together and help my code and me understand what to do.

```
{
  '@context': [
    'https://www.w3.org/2018/credentials/v1',
    'https://w3id.org/traceability/v1'
  ],
  issuer: 'did:key:z6MkqjFswaqkXJ7SRUZ8G9m1RtcjpXps1RZRKo4mFYZy5bWx',
  type: [ 'VerifiableCredential', 'ContactPoint' ],
  name: 'Verified phone number',
  description: 'This is a credential of phone number attribute that has been verified through sending an sms to the owner',
  issuanceDate: '2021-12-06T11:38:21Z',
  credentialSubject: {
    id: 'did:key:z6MkfwmZep5ZvkHfeXszxhxEuvkmGFRc8H9Nv9ZaQG4vhFzZ',
    identifier: '7870dab0-f8f5-11eb-b356-657b2e987fed',
    hhohoo: '+46456812311'
  }
}
```

**Comment by OR13** [comment]
@vongohren why do you think it should fail?

https://github.com/w3c-ccg/traceability-vocab/blob/gh-pages/contexts/traceability-v1.jsonld#L4

Trace Vocab now includes an `@vocab`... so that terms are given a "default context".

**Comment by vongohren** [comment]
@OR13 I think this would fail because I set a context, then I set a type for this data, and theeen I try to input an attribute that is not part of that type nor really any of those contexts.

Should it not complain?

I did for some strange reason start getting many of these errors: https://github.com/transmute-industries/verifiable-data/blob/main/packages/jsonld-schema/src/check/check.ts#L70, so trying to restructure a bit. But when it started to work again I was not able to force this error back with an attribute out of place, which I thought was the reason.

Ok, so if I use a different context/vocab it can fail because it will not have this Trace @vocab undefined Terms thing?

I think im might just be missing some key understanding of the value of this

**Comment by nissimsan** [comment]
Hey @vongohren, 

You seem focused on the order. Order doesn't matter, `@vocab` catches everything undefined. As @OR13 points out, this comes at a price - flexibility vs. hard core semantic perfection - and was debated significantly at trace-vocab (the killer argument was security). 

If the errors you got were a weeks ago, it sounds like that coincides with when the `@vocab` was merged. Your undefined parts should stop erroring from that point. Have you looked at the result - I bet it looks something like `<https://w3id.org/traceability/#undefinedTermhhohoo> "hhohoo" .`

**Comment by vongohren** [comment]
@nissimsan cool thanks for the pointers, I will try.
I got these errors today, but cached the vocab json for a while, and updated the cache today so maybe thats why.

@nissimsan you want to take a 15 minute talk since we are in the same timezone? If you want to help you  can find a slot here: https://calendly.com/snorre-diwala/30min. Its 30 min, but we use as short time as possible :)

Would be very helpful for a lightning intro over a video call

**Comment by vongohren** [comment]
I tried a bit around and found that yes, everything I send in is undefined term. The way you talked about it.
<img width="360" alt="Screenshot 2021-12-07 at 16 06 35" src="https://user-images.githubusercontent.com/1012055/145054263-83673f92-ebe9-407b-b4e3-ee0040ef5d0e.png">


But how do I target the ContactPoint email attrbitue then?  👇 

<img width="1217" alt="Screenshot 2021-12-07 at 16 06 18" src="https://user-images.githubusercontent.com/1012055/145054274-35089e34-2f6e-4e7c-a00a-7b8880ca6eff.png">

Since I mentione my VC up in the first comment: https://github.com/transmute-industries/verifiable-data/issues/129#issue-1072302499 that defines the type ContactPoint and attribute email under credentialSubject, I believe it should be attached somehow?

Identifier is attached, because it is a root value.

But does this mean that I have to put email under a
``` 
ContactPoint:{
 email:value
}
```

For it to make sense?

**Comment by OR13** [comment]
```
{
   "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
    "type": "ContactPoint",
    "name": "Hessel and Sons",
    "address": {
      "type": "PostalAddress",
      "streetAddress": "78619 Brayan Gardens",
      "addressLocality": "Padbergchester",
      "addressRegion": "West Virginia",
      "postalCode": "21476",
      "addressCountry": "Niger"
    },
    "email": "Gerhard.Kutch47@example.net",
    "phoneNumber": "555-999-1433"
}
```

```
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://schema.org/ContactPoint> .
_:b0 <https://schema.org/PostalAddress> _:b1 .
_:b0 <https://schema.org/email> "Gerhard.Kutch47@example.net" .
_:b0 <https://schema.org/name> "Hessel and Sons" .
_:b0 <https://schema.org/telephone> "555-999-1433" .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://schema.org/PostalAddress> .
_:b1 <https://schema.org/addressCountry> "Niger" .
_:b1 <https://schema.org/addressLocality> "Padbergchester" .
_:b1 <https://schema.org/addressRegion> "West Virginia" .
_:b1 <https://schema.org/postalCode> "21476" .
_:b1 <https://schema.org/streetAddress> "78619 Brayan Gardens" .
```

**Comment by vongohren** [comment]
Ok cool, I could not see anywhere in the spec that it was OK to set type in the credentialSubject. Does this not make the initial suggestion of presentation exchange query, where one use the context and type invalid? Or does one have to search for type inside credential subject?

Or does the spec say both is allowed?

I tested out this:
```
credentialSubject: {
   ContactPoint: {
      email: "email@email.com"
   }
}
```
<img width="542" alt="image" src="https://user-images.githubusercontent.com/1012055/145058732-ecda1313-9d76-4a56-ab82-6cb45740fd72.png">

**Comment by OR13** [comment]
@vongohren in the trace vocab, we are following the `type` convention, because it allows us to align JSON-LD with JSON Schema... in general, JSON-LD allows you to do the same thing many different ways.

**Comment by vongohren** [comment]
@OR13 OKOK, starting to make a bit sense.
This example from the VC data model: https://www.w3.org/TR/vc-data-model/#example-a-json-ld-context 
Works because it has flattly defined the two different attributes under and Extension12. And since there are no other parent parts, type under credential subject is not needed and it is valid?

And since tracebility defines sub nodes they have to explicitly be defined so that it makes sense for the graph.

Great stuff, think one piece clicked in place now
