### ISSUE TITLE
JSON Web Signature Browser vs Node differences

### ISSUE THREAD

**Issue by OR13** [transmute-industries/verifiable-data#140]
the module works in node, but fails in the browser.

It looks like the browser does not convert the public key to a buffer, but the node module does...

from the node module:

![Screen Shot 2022-01-16 at 2 53 25 PM](https://user-images.githubusercontent.com/8295856/149677654-a52f5ced-ab57-42a0-b7e7-35d7114cc930.png)

from the browser:

![Screen Shot 2022-01-16 at 2 54 16 PM](https://user-images.githubusercontent.com/8295856/149677683-6d67400c-77ef-4f7f-9aed-f80e20aee197.png)

**Comment by OR13** [comment]
![Screen Shot 2022-01-16 at 2 55 09 PM](https://user-images.githubusercontent.com/8295856/149677719-3d0832e4-4fb6-464c-8945-623f7ba87eaa.png)

**Comment by OR13** [comment]
the error is probably related to browser vs node differences between Buffer and Uint8Array... probably forgetting to case to Buffer somewhere.

**Comment by BenjaminMoe** [comment]
Maybe we could use a shim to use the Buffer object in the browser to keep the code the same? https://github.com/feross/buffer

**Comment by OR13** [comment]
pretty sure the tsdx bundler handles that for us... but something is wrong here.

**Comment by OR13** [comment]
This issue was resolved by upgrading to latest versions: see https://github.com/transmute-industries/api.did.actor/commit/f5733650232abff247425e6157212e850c4d793d

**Comment by OR13** [comment]
Also note that there was proof this was working here: https://transmute-industries.github.io/verifiable-data/smoke-test-react/
