### ISSUE TITLE
Upgrade our documentLoader behavior for DID URLs from resolvers to dereferencers 

### ISSUE THREAD

**Issue by BenjaminMoe** [transmute-industries/verifiable-data#150]
Digital Bazaar changed their document loader from a resolver to a derferencers 
This means to remain interopable, we need to change our document loaders to also implement this change
so that for the same input, we return the same document fragment

In terms of disambiguation, the difference between a resolver and a derferencer.
A resolver will load a document from a url, and return the entire document
A derferencer will load a specific fragment after loading the document from a url

In terms of dids, the use-case is that a resolver returns an entire did document, and 
a derferencer will return a specific key inside the did document.

This is a container issue on this repository to track and make sure that we update our document loaders
in this repository.

**Comment by BenjaminMoe** [comment]
https://github.com/digitalbazaar/jsonld-signatures/issues/141

**Comment by JaceHensley** [comment]
Related issue:
https://github.com/hellobloom/ssi-sdk/issues/31
