### ISSUE TITLE
Dependency not installed when installing vc.js

### ISSUE THREAD

**Issue by vongohren** [transmute-industries/verifiable-data#151]
Running the code with vc.js installed, it complains that jose is not found as a module.

So you might want to add it to the dependency tree and not as a dev dependency

**Comment by BenjaminMoe** [comment]
Thanks for opening an issue.

https://github.com/transmute-industries/verifiable-data/blob/main/packages/vc.js/package.json#L46
I'll upgrade it and open a PR for it.

**Comment by BenjaminMoe** [comment]
Looks like there is another place where this is popping up. 

![web-key](https://user-images.githubusercontent.com/86194145/155734420-f35e3e8a-2804-4bc8-8648-7ba89185f317.png)

**Comment by BenjaminMoe** [comment]
I think this has been addressed with PR: https://github.com/transmute-industries/verifiable-data/pull/175. Looks like the `jose-ld` module was missing a dependency, so this was coming up for packages that included it.
