### ISSUE TITLE
Can't resolve '@transmute/credentials-context' in /node_modules/@transmute/ed25519-signature-2018/dist

### ISSUE THREAD

**Issue by sacumesh** [transmute-industries/verifiable-data#202]
When I use the ed25519-signature-2018 I get the following error:
'@transmute/credentials-context' in '/Users/sachiththabandaranayake/Desktop/microrewards/micro-rewards-app/src/test-1/node_modules/@transmute/ed25519-signature-2018/dist'

The reason for this error is '@transmute/credentials-context' is listed as an devDependency but used as dependency in the '@transmute/ed25519-signature-2018' library
![Screenshot 2022-09-22 at 15 15 52](https://user-images.githubusercontent.com/79711366/191757463-cc3bb653-a526-4e1a-9c22-56f9f4abad6d.png)

**Comment by OR13** [comment]
We are dropping support for Ed25519Signature2018, I recommend using JWT now that VCDM v2  better supports it
