### ISSUE TITLE
`@transmute/json-web-signature` can't be used in browser without adding `Buffer` to the window object.

### ISSUE THREAD

**Issue by ipbyrne** [transmute-industries/verifiable-data#209]
Currently, this package can not be used in the browser without adding the snippet below to a `create-react-app` project:

```
import { Buffer } from "buffer";
window.Buffer = window.Buffer || Buffer;
```

This is because our package uses `@peculiar/webcrypto` which is expecting it to exist when its run in a browser environment.

Need to refactor using: https://www.npmjs.com/package/jose

**Comment by OR13** [comment]
See https://github.com/transmute-industries/verifiable-data/issues/211
