### ISSUE TITLE
'staticImplements' is not exported by node_modules/@transmute/ld-key-pair/dist/index.js

### ISSUE THREAD

**Issue by Nicolascoding27** [transmute-industries/verifiable-data#211]
Getting 

```
Rollup: Missing Export: node_modules/@transmute/ed25519-key-pair/dist/ed25519-key-pair.esm.js:3:9
           'staticImplements' is not exported by node_modules/@transmute/ld-key-pair/dist/index.js
```
When running 
`npm run build` and `npm run start
`

**Comment by BenjaminMoe** [comment]
Thanks for bringing this our attention. I created a ticket to track this.

**Comment by BenjaminMoe** [comment]
@Nicolascoding27 which directory are you running these commands from? The root directory, or a specific package?

**Comment by OR13** [comment]
Closing as stale, but I bet the issue remains, its likely something to do with the typescript version.

All these packages needs to be refreshed to remove tsdx.
