### ISSUE TITLE
vc.js: Server error causes `verify` to return as if a credential was revoked (if credential is revocable)

### ISSUE THREAD

**Issue by morgatron** [transmute-industries/verifiable-data#232]
It appears to me that when `verify` checks credential status, it must return either "revoked" or "not revoked". So any kind of server error will result in a message like:
```
 {
      status: 'bad',
      title: 'Revocation',
      description: 'This credential has been revoked.'
 }
```

This seems misleading. Shouldn't it return a warning of some kind instead,?

(We noticed this when setting up a revocation list (RevocationList2020status), and accidentally hosting the revocation list in the wrong place)

**Comment by BenjaminMoe** [comment]
https://github.com/w3c/vc-status-list-2021/issues/39

This is expected behavior, but it's not clearly define din the revocation list spec. I opened an issue to make this clear.

**Comment by morgatron** [comment]
It seems clear not that the expected behavior is indeed an error. However I note that the description is still misleading as in case of a server error the returned object states very clearly `This credential has been revoked..`. Could the description instead state something different, like `The status list could not be retrieved`?
