### ISSUE TITLE
Problem verifying VP

### ISSUE THREAD

**Issue by kuhlmannmarkus** [transmute-industries/verifiable-data#235]
I can issue a VC and also a VP containing the VC, but while verifying, I come across the following error in the verification result:

`{"verified":false,"credentials":{"verified":false,"results":[{"credentialId":"urn:uuid:mT4MZIUbY602zzDOLtUHQe1t1Po1IH6t","verified":false,"results":[{"proof":{"@context":["https://www.w3.org/2018/credentials/v1","https://w3id.org/security/suites/jws-2020/v1"],"type":"JsonWebSignature2020","created":"2023-03-18T10:16:10Z","verificationMethod":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#assertion","proofPurpose":"assertionMethod","jws":"eyJhbGciOiJFUzI1NksiLCJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdfQ..guWbw6zaghHElhEnY875jzTx4qBZq6AV2JtvrzBTn85SD2d8gTza-XJebsW_q7HlcLpY3mcoxAzqfLWCNr72kA"},"verified":false,"error":{"name":"jsonld.SyntaxError","details":{"code":"invalid local context","context":[null]},"message":"Invalid JSON-LD syntax; @context must be an object.","stack":"jsonld.SyntaxError: Invalid JSON-LD syntax; @context must be an object.\n    at _throwInvalidLocalContext (/home/issueuser/issue/node_modules/jsonld/lib/ContextResolver.js:212:9)\n    at ContextResolver.resolve (/home/issueuser/issue/node_modules/jsonld/lib/ContextResolver.js:68:9)\n    at api.process (/home/issueuser/issue/node_modules/jsonld/lib/context.js:65:50)\n    at api.expand (/home/issueuser/issue/node_modules/jsonld/lib/expand.js:211:23)\n    at Function.jsonld.expand (/home/issueuser/issue/node_modules/jsonld/lib/jsonld.js:325:24)\n    at Object.jsonld.frame (/home/issueuser/issue/node_modules/jsonld/lib/jsonld.js:474:38)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}],"error":{"name":"VerificationError","errors":[{"name":"jsonld.SyntaxError","details":{"code":"invalid local context","context":[null]},"message":"Invalid JSON-LD syntax; @context must be an object.","stack":"jsonld.SyntaxError: Invalid JSON-LD syntax; @context must be an object.\n    at _throwInvalidLocalContext (/home/issueuser/issue/node_modules/jsonld/lib/ContextResolver.js:212:9)\n    at ContextResolver.resolve (/home/issueuser/issue/node_modules/jsonld/lib/ContextResolver.js:68:9)\n    at api.process (/home/issueuser/issue/node_modules/jsonld/lib/context.js:65:50)\n    at api.expand (/home/issueuser/issue/node_modules/jsonld/lib/expand.js:211:23)\n    at Function.jsonld.expand (/home/issueuser/issue/node_modules/jsonld/lib/jsonld.js:325:24)\n    at Object.jsonld.frame (/home/issueuser/issue/node_modules/jsonld/lib/jsonld.js:474:38)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}]}}]},"presentation":{"verified":false,"results":[{"proof":{"@context":["https://www.w3.org/2018/credentials/v1","https://w3id.org/security/suites/jws-2020/v1"],"type":"JsonWebSignature2020","created":"2023-03-18T10:16:14Z","verificationMethod":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#authentication","proofPurpose":"authentication","challenge":"123","jws":"eyJhbGciOiJFUzI1NksiLCJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdfQ..LrtDefK1RrLsxuSpwadneavrhXdxRbgZdb5HTUAV8UtFkAgOhThM1Qy9LY1W1Ke7b2nmev_NvBY67_hYnQSU7w"},"verified":false,"error":{"name":"jsonld.SyntaxError","details":{"code":"invalid local context","context":[null]},"message":"Invalid JSON-LD syntax; @context must be an object.","stack":"jsonld.SyntaxError: Invalid JSON-LD syntax; @context must be an object.\n    at _throwInvalidLocalContext (/home/issueuser/issue/node_modules/jsonld/lib/ContextResolver.js:212:9)\n    at ContextResolver.resolve (/home/issueuser/issue/node_modules/jsonld/lib/ContextResolver.js:68:9)\n    at api.process (/home/issueuser/issue/node_modules/jsonld/lib/context.js:65:50)\n    at api.expand (/home/issueuser/issue/node_modules/jsonld/lib/expand.js:211:23)\n    at Function.jsonld.expand (/home/issueuser/issue/node_modules/jsonld/lib/jsonld.js:325:24)\n    at Object.jsonld.frame (/home/issueuser/issue/node_modules/jsonld/lib/jsonld.js:474:38)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}],"error":{"name":"VerificationError","errors":[{"name":"jsonld.SyntaxError","details":{"code":"invalid local context","context":[null]},"message":"Invalid JSON-LD syntax; @context must be an object.","stack":"jsonld.SyntaxError: Invalid JSON-LD syntax; @context must be an object.\n    at _throwInvalidLocalContext (/home/issueuser/issue/node_modules/jsonld/lib/ContextResolver.js:212:9)\n    at ContextResolver.resolve (/home/issueuser/issue/node_modules/jsonld/lib/ContextResolver.js:68:9)\n    at api.process (/home/issueuser/issue/node_modules/jsonld/lib/context.js:65:50)\n    at api.expand (/home/issueuser/issue/node_modules/jsonld/lib/expand.js:211:23)\n    at Function.jsonld.expand (/home/issueuser/issue/node_modules/jsonld/lib/jsonld.js:325:24)\n    at Object.jsonld.frame (/home/issueuser/issue/node_modules/jsonld/lib/jsonld.js:474:38)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}]}}}`

I cant find any object with an empty `@context` field.

This is the VP:

`{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "type": [
    "VerifiablePresentation"
  ],
  "holder": {
    "id": "did:ion:EiC84nonSBZU4Y40HOpovdMff5_1INkZ3hihiz705PVP9g"
  },
  "verifiableCredential": [
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/jws-2020/v1"
      ],
      "id": "urn:uuid:mT4MZIUbY602zzDOLtUHQe1t1Po1IH6t",
      "type": [
        "VerifiableCredential"
      ],
      "issuer": "did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw",
      "credentialSubject": {
        "id": "did:ion:EiC84nonSBZU4Y40HOpovdMff5_1INkZ3hihiz705PVP9g"
      },
      "issuanceDate": "2023-03-18T10:16:09Z",
      "proof": {
        "type": "JsonWebSignature2020",
        "created": "2023-03-18T10:16:10Z",
        "verificationMethod": "did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#assertion",
        "proofPurpose": "assertionMethod",
        "jws": "eyJhbGciOiJFUzI1NksiLCJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdfQ..guWbw6zaghHElhEnY875jzTx4qBZq6AV2JtvrzBTn85SD2d8gTza-XJebsW_q7HlcLpY3mcoxAzqfLWCNr72kA"
      }
    }
  ],
  "proof": {
    "type": "JsonWebSignature2020",
    "created": "2023-03-18T10:16:14Z",
    "verificationMethod": "did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#authentication",
    "proofPurpose": "authentication",
    "challenge": "123",
    "jws": "eyJhbGciOiJFUzI1NksiLCJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdfQ..LrtDefK1RrLsxuSpwadneavrhXdxRbgZdb5HTUAV8UtFkAgOhThM1Qy9LY1W1Ke7b2nmev_NvBY67_hYnQSU7w"
  }
}`

The issuing DID is resolved correctly:

`{"id":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw","@context":["https://www.w3.org/ns/did/v1"],"verificationMethod":[{"id":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#authentication","controller":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw","type":"JsonWebKey2020","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"b2B8UjPtFhq2nnDfb0BLhW9QZGcXSNbVb4hYHspXFhU","y":"MDu4V6U-NBBjO1QwT_UjI114JJaSqlYQ1pbFwd9f5RA"}},{"id":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#assertion","controller":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw","type":"JsonWebKey2020","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"R7D9TpRo6BTdmuNN5qR4kOsYexBuiRRO2w6ykrzG4uQ","y":"Zn3-CMA9yntIWM1O28xJK79uwD2Eec70ipJcj363I0c"}}],"authentication":["did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#authentication"],"assertionMethod":["did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#assertion"]}`

Any hints on what Im doing wrong?
Thanks in advance!

**Comment by OR13** [comment]
probably the document loader is not handling the context, try logging the document loader URLs and see if it handles each one.

**Comment by kuhlmannmarkus** [comment]
Thank you so much for your reply! I still cant quite figure out whats wrong here.

This is my document loader:

`const documentLoader = loader.documentLoaderFactory.build({
  ["did:ion"]: async (did) => {
    let didDoc = await ion.resolve(did);
    return didDoc.didDocument;
  },
  ["http"]: async (did) => {
    let { data } = await axios.get(did);
    return data;
  },
});`

In the process of issuing and verifying the VC and the corresponding VP, the document loader loads https://www.w3.org/2018/credentials/v1 and https://w3id.org/security/suites/jws-2020/v1 multiple times, so I guess this is successful. Just after loading the ION DID document, I get the error message. But it looks like a valid JSON LD document to me.   The URL in the context of the DID document (https://www.w3.org/ns/did/v1) is never loaded. I dont understand whats missing here.

Any help is appreciated.

**Comment by OR13** [comment]
The ION DID Document is missing a context definition, not sure if that is the problem though...

If can be fixed by adding:

```json
"@context":["https://www.w3.org/ns/did/v1", {"@vocab":"https://www.w3.org/ns/did/controller-dependent#"} ]
```

Adding a default vocabulary cuts down on lots of JSON-LD errors when terms are not defined.

I can see that `publicKeyJwk` is not defined in your ION DID Documents context.

See this example:

- https://github.com/transmute-industries/verifiable-data/tree/main/packages/jsonld-document-loader#resolve-did-document-with-remote-did-resolver

Also make sure to check versions.

I see from the error, it is being thrown by jsonld.js...

- https://github.com/digitalbazaar/jsonld.js/search?q=_throwInvalidLocalContext

```
"details":{"code":"invalid local context","context":[null]}
```

Somehow you have a null in your document loader results.

I suggest, creating a minimal reproduction with just a documentLoader that throws, and the JSON-LD object you are processing, (test with canonize).

Then add context's one by one to the document loader until canonize succeeds.

**Comment by kuhlmannmarkus** [comment]
Dear @OR13 ,

adding the "controller dependent" context object did the trick. I can now verify the VP.

`{"verified":true,"credentials":{"verified":true,"results":[{"credentialId":"urn:uuid:wwN4mQGAxaMjKmpt9mQlOaNyUP9PeHQx","verified":true,"results":[{"proof":{"@context":["https://www.w3.org/2018/credentials/v1","https://w3id.org/security/suites/jws-2020/v1"],"type":"JsonWebSignature2020","created":"2023-03-20T06:14:20Z","verificationMethod":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#assertion","proofPurpose":"assertionMethod","jws":"eyJhbGciOiJFUzI1NksiLCJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdfQ..r0rgc2oFstvJ_XuMvu9XHa_dcSIp7eBTPIge05kD7xETDp6V6hujCtRFx-9FCZZ00Oq6AEokSgIsCQUPjKqYGw"},"verified":true,"purposeResult":{"valid":true}}]}]},"presentation":{"verified":true,"results":[{"proof":{"@context":["https://www.w3.org/2018/credentials/v1","https://w3id.org/security/suites/jws-2020/v1"],"type":"JsonWebSignature2020","created":"2023-03-20T06:14:23Z","verificationMethod":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw#authentication","proofPurpose":"authentication","challenge":"123","jws":"eyJhbGciOiJFUzI1NksiLCJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdfQ..DZckjhIxsXgj4CytnPlKQWyYmU0HP7zha-9Uj_y1lslbu2ZKcJAsR4u0f6r-jY2UWIeGG-3pTGe8LGq_-HMyfA"},"verified":true,"purposeResult":{"valid":true,"controller":{"id":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw","@context":["https://www.w3.org/ns/did/v1",{"@base":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw"},{"@vocab":"https://www.w3.org/ns/did/controller-dependent#"}],"verificationMethod":[{"id":"#authentication","controller":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw","type":"JsonWebKey2020","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"b2B8UjPtFhq2nnDfb0BLhW9QZGcXSNbVb4hYHspXFhU","y":"MDu4V6U-NBBjO1QwT_UjI114JJaSqlYQ1pbFwd9f5RA"}},{"id":"#assertion","controller":"did:ion:EiBG1ef40swSyamH4clA3ISNpSLatQkXEkst1GJE1Fbnqw","type":"JsonWebKey2020","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"R7D9TpRo6BTdmuNN5qR4kOsYexBuiRRO2w6ykrzG4uQ","y":"Zn3-CMA9yntIWM1O28xJK79uwD2Eec70ipJcj363I0c"}}],"authentication":["#authentication"],"assertionMethod":["#assertion"]}}}]}}`

Thank you so much!
