### ISSUE TITLE
Credential Verification fails if `proof` property has a local `@context`

### ISSUE THREAD

**Issue by Yengas** [transmute-industries/verifiable-data#238]
## Bug Description

```
import { verifiable } from "@transmute/vc.js";

const result = await verifiable.credential.verify({ credential: vc, format: ["vc"], suite: [suite], documentLoader });
```

`credential.verify` fails if the given Verifiable Credential contains an embedded proof with local `@context` definition.

Example VC structure which is failing:
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  ...,
  "issuer": "did:web:yigitcan.dev",
  "proof": {
    "@context": [
      "https://w3id.org/security/suites/jws-2020/v1"
    ],
    ...
  }
}
```

When `vc.proof[@context]` values are appended to `vc[@context]`, the VC is verified correctly. Example:

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1",
     "https://w3id.org/security/suites/jws-2020/v1"
  ],
  ...,
  "issuer": "did:web:yigitcan.dev",
  "proof": {
    ...
  }
}
```

## Easy Reproduce Steps

Data and code maybe found in [this gist ](https://gist.github.com/Yengas/93d3499c0caf8d3262a78657212e6d17) to reproduce the issue.

1. Try executing the `03-reproduce.js`. You should get a verification error.
2. In the same script; Either change the `vc` variable to VC data contained in `01-good-example-data.json`, or manually add proper context to VC document.
3. Executing the script, you should have verification succeed.

## Environment
- Transmute Libraries: `0.7.0-unstable.80`

**Comment by Yengas** [comment]
The reason seems to be this line:

https://github.com/transmute-industries/verifiable-data/blob/e89a530073862f31e7f1d2904c53179625c2cd14/packages/linked-data-proof/src/ProofSet.ts#L106

`ProofSet#_getProofs` is expanding the `proof` after Document `@context` is set. Causing the Document context to be overwritten if the Proof has a context.

**Comment by OR13** [comment]
Thanks for this bug report!

proof property should not have a local context... 


https://github.com/w3c/vc-jws-2020

Was withdrawn as a work item, and we will not be fixing issues with it, we are focused on implementing v2 data model in JWT


We'll probably deprecate the package in the future.
