### ISSUE TITLE
JsonWebSignature2020 RSA support

### ISSUE THREAD

**Issue by fabrii** [transmute-industries/verifiable-data#239]
Hi! I wanted to know if there are any plans to support RSA Signatures on https://github.com/transmute-industries/verifiable-data/tree/main/packages/json-web-signature

Thanks!

**Comment by OR13** [comment]
There are not, but we do plan to support vc-jwt 2.0, which will support everything registered with IANA, of course its still best to move off RSA if you have the ability to.

**Comment by fabrii** [comment]
Unfortunately, we can't change the keys. This is the only JsonWebSignature javascript suite that I found, and it seems I cannot use RsaSignature2018 neither because of a spec bug. 

If needed, would you accept PRs?

**Comment by OR13** [comment]
Yes, we accept PRs.

**Comment by OR13** [comment]
just an FYI, the working group has decided to withdraw that work item: https://github.com/w3c/vc-jws-2020

Like many community signature schemes, it will keep working as long as the contexts resolve,  but I would avoid switching to it if you can.

**Comment by fabrii** [comment]
Thanks! I am closing this issue
