### ISSUE TITLE
X25519 in JsonWebKey?

### ISSUE THREAD

**Issue by brianorwhatever** [transmute-industries/verifiable-data#70]
Hey @OR13 is there a reason that OKP / X25519 is not supported by this lib or is it just not in there yet? If it's the latter I can attempt a PR
https://github.com/transmute-industries/verifiable-data/blob/577fd3663858ac6ac3f4b4091e10246fead7a4bb/packages/json-web-signature/src/JsonWebKey.ts#L23

**Comment by brianorwhatever** [comment]
I'm guessing we'll also need to add 'ECDH-ES+A256KW' to https://github.com/transmute-industries/verifiable-data/blob/main/packages/jose-ld/src/types/JWA_ALG.ts

**Comment by brianorwhatever** [comment]
I see now that x25519 isn't meant for signatures and only encryption? 😅
It does seem like it should be added to `JsonWebKey` though so that we can use this fine library for didcomm encryption. Let me know how you think I should proceed

**Comment by brianorwhatever** [comment]
I believe this isn't a well formed `JsonWebKey2020` as it doesn't have a `publicKeyJwk` :)
https://github.com/transmute-industries/verifiable-data/blob/577fd3663858ac6ac3f4b4091e10246fead7a4bb/packages/x25519-key-pair/src/X25519KeyPair.ts#L21

**Comment by OR13** [comment]
I think you are looking for something like this:
 https://github.com/transmute-industries/verifiable-data/blob/main/packages/jose-ld/src/__tests__/JWE.x25519.ECDH-ES.test.ts
 
 We use this for our universal wallet import / export format... and there is a reported bug in the latest version I have not gotten around to fixing:
 
 https://github.com/transmute-industries/verifiable-data/pull/66

**Comment by OR13** [comment]
@brianorwhatever I am reading this as a feature request for adding X25519 support for JsonWebKey... we already support similar functionality for NIST curves here: https://github.com/transmute-industries/verifiable-data/blob/main/packages/jose-ld/src/__tests__/JWE.p384.ECDH-ES.test.ts

it wouldn't be that much extra work to wrap X25519KeyPair in the same way we are wrapping WebCryptoKeyPair.

**Comment by brianorwhatever** [comment]
The JWE.x25519.ECDH-ES is exactly what I am looking for not sure how I missed it last week. Thanks for deciphering my nonsense 😄

**Comment by OR13** [comment]
@brianorwhatever I am nervous about our implementation of it.... I really prefer to compare cross implementation tests for these kinds of things... particularly with https://www.npmjs.com/package/jose

**Comment by OR13** [comment]
Also related tests: https://github.com/transmute-industries/did-key.js/blob/main/packages/did-key-x25519/src/__tests__/jose.test.ts

**Comment by brianorwhatever** [comment]
So adding something like this was along the lines of where I was going before I realized that it doesn't really make sense in a json-web-signatures package.. approaches I can think of:
1. move JsonWebKey class into a new json-web-key package
2. yolo it into the json-web-signatures package
3. add it into the web-crypto-key-pair package here https://github.com/transmute-industries/verifiable-data/blob/e759685b9ef5283f20cbf84cfaf2901b8f7e6356/packages/web-crypto-key-pair/src/key/getCryptoKeyFromJsonWebKey2020.ts

if you pick an option of those I can create a PR. I'm leaning towards 3 myself

**Comment by OR13** [comment]
yeah, I agree leaning towards 3... the main reason I didn't do that upfront was (hopelessly) dreaming of a zero dependencies key representation that used `window.crypto.subtle` when available... but that would never support Ed25519 / X25519 / Secp256k1 / Bls12381.... that seems like a good enough reason to add support for them, and drop the 0 dependency dream.

**Comment by OR13** [comment]
I suggest using did:jwk moving forward... see https://github.com/transmute-industries/did-transmute
