### ISSUE TITLE
Error: 'staticImplements' is not exported by node_modules/@transmute/ld-key-pair/dist/index.js

### ISSUE THREAD

**Issue by lemoustachiste** [transmute-industries/verifiable-data#73]
Hi,

I am implementing some did verification process in a library that runs both in the browser and on node. One of the dependencies (I believe it would be @transmute/did-key-secp256k1) relies on this library.

When I am bundling with rollup, I get the following error: 

```
[!] Error: 'staticImplements' is not exported by node_modules/@transmute/ld-key-pair/dist/index.js, imported by node_modules/@transmute/secp256k1-key-pair/dist/secp256k1-key-pair.esm.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@transmute/secp256k1-key-pair/dist/secp256k1-key-pair.esm.js (3:9)
1: import { __decorate } from 'tslib';
2: import secp256k1 from 'secp256k1';
3: import { staticImplements } from '@transmute/ld-key-pair';
                  ^
```

indeed the entry file looks like this:
```
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./ld-key-pair.cjs.production.min.js')
} else {
  module.exports = require('./ld-key-pair.cjs.development.js')
}
```

And it does not seem rollup is capable of interpreting this dynamic import? Or do you know of a way?

Thanks

**Comment by lemoustachiste** [comment]
Would this achieve the same desired behavior on your part? https://nodejs.org/api/packages.html#packages_conditional_exports

**Comment by OR13** [comment]
we've moved aware for a lot of the JSON-LD stuff we were doing before, perhaps this library will be of better use:

https://github.com/transmute-industries/did-transmute
