### ISSUE TITLE
  The property "created" in the input was not defined in the context.

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/verifiable-data#74]
I tried to run the following code for the universal wallet vc plugin and got the error below. Does anyone know why it happened?
https://github.com/transmute-industries/verifiable-data/tree/main/packages/universal-wallet-vc-plugin/src/__tests__/JsonWebSignature2020
`
const vc = await plugin.issue({
        credential: { ...credential, issuer: key.controller },
        options: {
          suite,
          documentLoader
        }
      });
console.log(JSON.stringify(vc));
`

**Comment by thomas-tran** [comment]
@OR13 I tried to use the latest package but this issue is still available. Do you have any idea why it did not work?
0.7.0-unstable.7

`
import * as Factory from 'factory.ts';
import * as Vc from '@transmute/universal-wallet-vc-plugin';
import key0 from './key-0.json';
import credential from './credential.json';

import { documentLoader } from './documentLoader';
import { Wallet, walletFactory, walletDefaults } from '@transmute/universal-wallet';
import { Ed25519Signature2018, Ed25519VerificationKey2018 } from '@transmute/ed25519-signature-2018';

export interface MyWallet extends Wallet, Vc.VcPlugin { }

const factory = Factory.Sync.makeFactory<MyWallet>({
    ...walletDefaults,
    ...Vc.factoryDefaults
});

factory.combine(walletFactory)
    .combine(Vc.pluginFactory);


export const wallet = factory.build();

async function main () {
    const key = await Ed25519VerificationKey2018.from(key0);
    const suite = new Ed25519Signature2018({
        key,
        date: "2021-06-19T18:53:11Z"
    });

    const vc = await wallet.issue({
        credential: {
            ...credential,
            issuer: key0.controller
        },
        options: {
            suite,
            documentLoader,
        }
    });
    console.log(vc);
}

main();
`

**Comment by OR13** [comment]
its possible that the universal wallet is pinned to older versions, that have a bug.

sorry for the late reply, hav you tried the latest version?

**Comment by thomas-tran** [comment]
Hi @OR13 I used the latest wallet and it did not work. Here is the example

https://codesandbox.io/s/sparkling-field-emgbw

**Comment by OR13** [comment]
@thomas-tran thanks for reporting this!

**Comment by wgcv** [comment]
Any news? I can't reproduce the example of bbs-bls12381-signature-2020 with the same error

**Comment by acarnagey** [comment]
`@transmute/universal-wallet-vc-plugin` currently has a pinned version of `@transmute/vc.js` that is older that has this bug.  In the meantime you should be able to issue a credential by not using the wallet plugin and using vc.js directly with the most recent version.
```js
const Vc = require("@transmute/vc.js");
const vc1 = await Vc.verifiable.credential.create({
    credential: {
      ...credential,
      issuer: key0.controller,
    },
    format: ["vc"],
    documentLoader,
    suite,
  });
```
