### ISSUE TITLE
Any test case for VP Auth?

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/verifiable-data#82]
@OR13 Do you have any test case or instruction for the passwordless authentication using VP exchange?

**Comment by OR13** [comment]
hmm, there is not currently a good "standard" for that.

See also:

- https://w3c-ccg.github.io/vp-request-spec/
- https://github.com/decentralized-identity/waci-presentation-exchange

(OIDC SIOP also)...


The naive solution is:

1. holder claims to be  identifier
2. verifier challenges holder with randomness
3. holder presents VP with no credentials over the challenge.

```
{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "type": "VerifiablePresentation",
  "holder": "did:example:12345",
  "proof": {
    "proofPurpose": "authentication",
    "type": "Ed25519Signature2018",
    "challenge": "99612b24-63d9-11ea-b99f-4f66f3e4f81a",
    "domain": "example.com",
    "created": "2020-06-06T21:05:13Z",
    "verificationMethod": "did:example:12345#z6Mkkg...",
    "jws": "..."
  }
}
```
