### ISSUE TITLE
Do you have an example of document loader for microsoft ion or element?

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/verifiable-data#84]
Hi @OR13 , do you have an example of document loader for Microsoft ion or element that using the verifiable credential?

**Comment by OR13** [comment]
I find its best to write the documentLoader from scratch and make sure it handles all contexts you care about with no network requests... and all did methods you care about with minimal networks requests to infrastructure you control.

here is an example:

https://github.com/decentralized-identity/JWS-Test-Suite/blob/main/implementations/transmute/services/documentLoader.js

If the did method is defined correctly, it should behave the same way.

for example:

A key used to authenticate: https://github.com/transmute-industries/sidetree.js/blob/main/packages/test-vectors/src/did-method/v1-did-method-secp256k1-operations.json#L106

A key used to issue: https://github.com/transmute-industries/sidetree.js/blob/main/packages/test-vectors/src/did-method/v1-did-method-secp256k1-operations.json#L109

**Comment by OR13** [comment]
To answer your question directly... you can configure your documentLoader to use a any DID Method resolver you trust, including the universal resolver at DIF.

**Comment by OR13** [comment]
@thomas-tran if you are trying to use these libraries with ION, you may find this PR helpful: https://github.com/transmute-industries/verifiable-data/pull/115

Closing this issue, but always feel free to open other issues for any new questions.
